# Generated by Django 3.1.6 on 2021-02-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='reservas/photos/h4.jpg', upload_to='ImagenHabitaciones')),
                ('titulo', models.CharField(max_length=25)),
                ('despr1', models.CharField(max_length=25)),
                ('despr2', models.CharField(max_length=25)),
                ('despr3', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Habitacio',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
    ]
